name: Docker Compose Actions Workflow

on:
  push:
    paths:
      - '**'
      - '!README.md'

jobs:
  docker-compose-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: docker-compose build && run && test
        run: docker-compose up -d --build --scale liquidity-service-process=10 --exit-code-from test-service

      - name: "test: all services running"
        run: /bin/sh test/all_services_running.sh

        # It's nice to see logs. Especially if the tests fail.
      - name: docker-compose logs
        if: ${{ always() }}
        run: docker-compose logs
